version: '3.1'

services:
  db:
    image: postgres:14
    ports:
      - 5435:5432
    restart: always
    environment:
      POSTGRES_USER: truphone
      POSTGRES_PASSWORD: truphone
      POSTGRES_DB: truphone